'use client';

import Link from 'next/link';
import { useState } from 'react';
import { usePathname, useSearchParams } from 'next/navigation';
import { Button } from '@/components/ui/button';
import { JourneyActions } from './journey-actions';
import { MediaJourneyGuide, PageEvidence, useEpisodeJourney, useJourneyLocale } from './media-journey';
import { journeyGuide, journeyNextAction, journeyReason, journeyState } from '@/lib/studio/journey-guide';
import { episodePolicyRows, policyOrigin } from '@/lib/studio/episode-policy';
import type { JourneyGeneration, JourneyStep } from '@/lib/api/cms/media-journey';

export function EpisodeContextTab({ id, mode }: { id: string | null; mode: 'policy' | 'diagnostics' }) {
    const ar = useJourneyLocale() === 'ar';
    if (!id) return <section className="rounded-md border bg-card p-4"><h2 className="text-lg font-semibold">{mode === 'policy' ? (ar ? 'سياسة الحلقة' : 'Episode policy') : (ar ? 'تشخيص الحلقة' : 'Episode diagnostics')}</h2><p className="mt-2 text-sm text-muted-foreground">{ar ? 'اختر حلقة من سير العمل لعرض إعداداتها وأدلتها. الأقسام أدناه تخص المستأجر وليست حلقة محددة.' : 'Select an episode in Workflow to see its settings and evidence. The sections below cover the tenant, not a selected episode.'}</p><Link className="mt-3 inline-block text-sm text-primary underline" href="?tab=workflow">{ar ? 'اختيار حلقة' : 'Choose an episode'}</Link></section>;
    return <SelectedEpisodeContext key={id} id={id} mode={mode} />;
}

function SelectedEpisodeContext({ id, mode }: { id: string; mode: 'policy' | 'diagnostics' }) {
    const locale = useJourneyLocale(); const ar = locale === 'ar';
    const text = (en: string, arabic: string) => ar ? arabic : en;
    const params = useSearchParams(); const pathname = usePathname();
    const query = useEpisodeJourney(id); const data = query.data;
    const [chaptersOpen, setChaptersOpen] = useState(false); const [eventsOpen, setEventsOpen] = useState(false);
    const href = (tab: string, guide?: string) => { const next = new URLSearchParams(params.toString()); next.set('tab', tab); if (guide) next.set('guide', guide); return `${pathname}?${next}`; };
    const stamp = (value?: string) => value ? new Date(value).toLocaleString() : text('Not recorded', 'غير مسجل');
    const currentStep = data?.steps.find(step => ['failed', 'reconciling', 'running'].includes(step.state))
        ?? data?.steps.find(step => step.required && !['completed', 'not_required'].includes(step.state));
    const currentStepHelp = currentStep ? journeyGuide[currentStep.key]?.[locale] : undefined;
    const stepAction = (step: JourneyStep) => journeyNextAction(step.reason_code, locale, step.key);
    const generation = (label: string, value?: JourneyGeneration | null) => <section className="border-b py-4 last:border-0"><h3 className="font-medium">{label}</h3>{value ? <><p className="mt-2 text-sm">{journeyState(value.state, locale)} · {value.completed_units}/{value.expected_units} {text('verified cuts', 'مقاطع متحققة')}</p><p className="mt-1 text-xs text-muted-foreground">{text('Plan origin', 'مصدر الخطة')}: {value.plan_origin ?? text('Origin unavailable', 'المصدر غير متاح')}</p><code className="mt-2 block break-all text-xs text-muted-foreground">{value.id}</code></> : <p className="mt-2 text-sm text-muted-foreground">{text('No generation recorded in this snapshot.', 'لا يوجد إصدار مسجل في هذه اللقطة.')}</p>}</section>;
    return <section className="space-y-4" dir={ar ? 'rtl' : 'ltr'}>
        <header className="flex flex-wrap items-start justify-between gap-3 rounded-md border bg-card p-4"><div><h2 className="text-lg font-semibold">{mode === 'policy' ? text('Episode policy', 'سياسة الحلقة') : text('Episode diagnostics', 'تشخيص الحلقة')}</h2><p className="mt-2 text-lg" dir="auto">{data?.parent.title ?? text('Loading episode…', 'جارٍ تحميل الحلقة…')}</p><p className="mt-1 text-sm text-muted-foreground">{mode === 'policy' ? text('Effective settings for this episode. Global changes are separate.', 'الإعدادات الفعلية لهذه الحلقة. التغييرات العامة منفصلة.') : text('Current durable evidence, not historical run badges. A heartbeat is not processing progress.', 'أدلة الحالة الحالية وليست شارات التشغيل التاريخية. تجديد الحجز لا يثبت تقدم المعالجة.')}</p></div><div className="flex flex-wrap gap-2"><Link className="rounded-md border px-3 py-2 text-sm hover:bg-muted" href={href('workflow')}>{text('Open journey', 'فتح الرحلة')}</Link><MediaJourneyGuide /></div></header>
        {query.isError && <div role="alert" className="rounded-md border border-destructive/40 p-3 text-sm"><p>{query.error.message}</p><p>{data ? text('Showing a cached snapshot; refresh before acting.', 'تُعرض لقطة مخزنة؛ حدّثها قبل اتخاذ إجراء.') : text('Episode evidence is unavailable. Other sections are independent.', 'أدلة الحلقة غير متاحة. الأقسام الأخرى مستقلة.')}</p><p className="mt-1 text-xs text-muted-foreground">{journeyNextAction('evidence_unavailable', locale)}</p><div className="mt-2 flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={() => void query.refetch()}>{text('Refresh evidence', 'تحديث الأدلة')}</Button><Link className="inline-flex items-center rounded-md border px-3 py-2 text-xs font-medium hover:bg-muted" href="/platform/system-health">{text('Open System Health', 'فتح صحة النظام')}</Link></div></div>}
        {data && <>
            <p className="text-xs text-muted-foreground">{text('Last successful snapshot', 'آخر لقطة ناجحة')}: {new Date(query.dataUpdatedAt).toLocaleString()}</p>
            {mode === 'policy' && <Link className="inline-block text-sm text-primary underline" href="/platform/media">{text('Edit tenant acquisition and STT settings in Media Library', 'تعديل إعدادات التنزيل والتفريغ للمستأجر في مكتبة الوسائط')}</Link>}
            {mode === 'diagnostics' && <section className="rounded-md border border-[#D7A83E]/45 bg-[#D7A83E]/10 p-4" aria-labelledby="episode-next-step">
                <h3 id="episode-next-step" className="font-semibold">{text('What should I do next?', 'ما الإجراء التالي؟')}</h3>
                <p className="mt-1 text-sm text-muted-foreground">{text('Use the current durable state below to choose one safe action. A wait, dependency, or reconciliation state is not the same as a failed job.', 'استخدم الحالة الحالية الموثقة أدناه لاختيار إجراء آمن. الانتظار أو التبعية أو التسوية ليست فشلاً في المهمة.')}</p>
                {currentStep ? <div className="mt-3 grid gap-3 md:grid-cols-2">
                    <div className="rounded-md border border-border/70 bg-background/60 p-3">
                        <p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">{text('Current step', 'الخطوة الحالية')}</p>
                        <p className="mt-1 font-medium">{currentStepHelp?.title ?? currentStep.key} · {journeyState(currentStep.state, locale)}</p>
                        <p className="mt-2 text-sm text-muted-foreground">{journeyReason(currentStep.reason_code, locale)}</p>
                    </div>
                    <div className="rounded-md border border-border/70 bg-background/60 p-3">
                        <p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">{text('Safe next action', 'الإجراء الآمن التالي')}</p>
                        <p className="mt-1 text-sm">{stepAction(currentStep)}</p>
                        {!!currentStep.depends_on?.length && <p className="mt-2 text-xs text-muted-foreground">{text('Depends on', 'يعتمد على')}: {currentStep.depends_on.map(key => journeyGuide[key]?.[locale].title ?? key).join(', ')}</p>}
                    </div>
                </div> : <p className="mt-3 text-sm">{text('No incomplete required step is reported. Inspect publication readiness or the latest generation before starting replacement work.', 'لا توجد خطوة مطلوبة غير مكتملة. افحص جاهزية النشر أو آخر إصدار قبل بدء عمل استبدال.')}</p>}
                {data.capacity.waiting && <p className="mt-3 text-sm">{journeyNextAction('shared_capacity', locale)}{data.capacity.episode_id ? <> <Link className="font-medium underline" href={`${pathname}?tab=diagnostics&item=${data.capacity.episode_id}`}>{data.capacity.title ?? text('Open slot holder', 'فتح الحلقة الحاجزة')}</Link>.</> : null}</p>}
            </section>}
            {mode === 'policy' ? <div className="grid items-start gap-4 xl:grid-cols-[minmax(0,1.6fr)_minmax(0,1fr)]">
                <section className="overflow-hidden rounded-md border bg-card"><div className="overflow-x-auto"><table className="w-full min-w-[480px] text-start text-sm"><caption className="border-b p-4 text-start text-xs text-muted-foreground">{text('Highest policy override', 'أعلى تجاوز للسياسة')}: {policyOrigin(data.policy_source, locale)}. {text('Individual fields may still be inherited; CMS does not expose field-level origins.', 'قد تبقى بعض الحقول موروثة؛ لا يعرض CMS مصدراً لكل حقل.')}</caption><thead className="border-b text-muted-foreground"><tr>{[text('Setting', 'الإعداد'), text('Effective value', 'القيمة الفعلية'), text('Origin', 'المصدر')].map(label => <th key={label} className="px-4 py-3 text-start font-medium">{label}</th>)}</tr></thead><tbody>{episodePolicyRows(data, locale).map(row => <tr key={row.key} className="border-b last:border-0"><th scope="row" className="px-4 py-3 text-start font-medium">{row.label}</th><td className="px-4 py-3">{row.value}</td><td className="px-4 py-3 text-xs text-muted-foreground">{row.origin}</td></tr>)}</tbody></table></div></section>
                <aside className="rounded-md border bg-card p-4"><h3 className="font-semibold">{text('What this means', 'ماذا يعني ذلك؟')}</h3><div className="divide-y">{['download', 'transcript', 'planning', 'review'].map(key => <section key={key} className="py-4"><Link className="text-sm font-medium hover:underline" href={href(mode, key)}>{journeyGuide[key][locale].title}</Link><p className="mt-2 text-sm text-muted-foreground">{journeyGuide[key][locale].action}</p></section>)}</div><p className="text-xs text-muted-foreground">{text('Changing settings does not rewrite a frozen plan or recut published media. Use a versioned draft for deliberate replacement.', 'تغيير الإعدادات لا يعدّل خطة مثبتة أو يعيد قص الوسائط المنشورة. استخدم مسودة ذات إصدار للاستبدال الصريح.')}</p></aside>
            </div> : <>
                {data.progress_unavailable && <p role="status" className="text-sm text-muted-foreground">{text('Some timing evidence is unavailable. This does not mean processing has stopped.', 'بعض أدلة التوقيت غير متاحة. هذا لا يعني توقف المعالجة.')}</p>}
                {data.item?.lane === 'failed' && data.item.latest_error && <p role="alert" className="break-words rounded-md border border-destructive/40 p-3 text-sm text-destructive">{data.item.latest_error}</p>}
                {data.capacity.waiting && <p className="rounded-md border p-3 text-sm">{journeyReason('shared_capacity', locale)} {data.capacity.episode_id && <Link className="underline" href={`${pathname}?tab=diagnostics&item=${data.capacity.episode_id}`}>{data.capacity.title ?? text('Open slot holder', 'فتح الحلقة الحاجزة')}</Link>}</p>}
                <div className="grid items-start gap-4 xl:grid-cols-[minmax(0,1.6fr)_minmax(0,1fr)]">
                    <section className="overflow-x-auto rounded-md border bg-card"><table className="w-full min-w-[540px] text-sm"><thead className="border-b text-muted-foreground"><tr>{[text('Step', 'الخطوة'), text('State / reason', 'الحالة / السبب'), text('Last confirmed progress', 'آخر تقدم مؤكد')].map(label => <th key={label} className="px-4 py-3 text-start font-medium">{label}</th>)}</tr></thead><tbody>{data.steps.map(step => <tr key={step.key} className="border-b last:border-0"><th className="px-4 py-3 text-start align-top font-medium"><Link href={href(mode, step.key)} className="hover:underline">{journeyGuide[step.key]?.[locale].title ?? step.key}</Link></th><td className="px-4 py-3 align-top"><span className={step.state === 'failed' ? 'text-destructive' : ''}>{journeyState(step.state, locale)}</span>{['waiting', 'failed', 'reconciling', 'queued', 'blocked'].includes(step.state) && <><p className="mt-1 break-words text-xs text-muted-foreground">{journeyReason(step.reason_code, locale)}</p><p className="mt-2 break-words border-t border-border/60 pt-2 text-xs"><span className="font-medium text-foreground">{text('Next', 'التالي')}:</span> {stepAction(step)}</p></>}{step.waiting_category && <p className="mt-1 text-xs text-muted-foreground">{text('Wait category', 'فئة الانتظار')}: {step.waiting_category}</p>}</td><td className="px-4 py-3 align-top text-xs text-muted-foreground">{stamp(step.last_progress_at ?? step.completed_at)}{step.completed != null && <p className="mt-1">{step.completed}/{step.total} {text('verified cuts', 'مقاطع متحققة')}</p>}</td></tr>)}</tbody></table></section>
                    <aside className="rounded-md border bg-card px-4">{generation(text('Candidate generation', 'الإصدار المرشح'), data.candidate_generation)}{generation(text('Published generation', 'الإصدار المنشور'), data.published_generation)}<p className="pb-4 text-xs text-muted-foreground">{text('Candidate completion and publication are separate. Existing publication stays available while a replacement is prepared.', 'اكتمال الإصدار المرشح يختلف عن نشره. يبقى المنشور متاحاً أثناء إعداد البديل.')}</p></aside>
                </div>
                <section className="rounded-md border bg-card p-4"><h3 className="mb-3 font-semibold">{text('Available actions and recovery', 'الإجراءات المتاحة والاسترداد')}</h3>{data.item ? <JourneyActions item={data.item} /> : <p className="text-sm text-muted-foreground">{text('Action evidence unavailable.', 'أدلة الإجراءات غير متاحة.')}</p>}</section>
                <details className="rounded-md border p-4" onToggle={event => setChaptersOpen(event.currentTarget.open)}><summary className="cursor-pointer font-medium">{text('Chapter readiness and family holds', 'جاهزية الفصول ومتطلبات الحلقة')}</summary>{chaptersOpen && <div className="mt-4"><PageEvidence id={data.parent.id} section="chapters" /></div>}</details>
                <details className="rounded-md border p-4" onToggle={event => setEventsOpen(event.currentTarget.open)}><summary className="cursor-pointer font-medium">{text('Execution and event history', 'التنفيذ وسجل الأحداث')}</summary>{eventsOpen && <div className="mt-4 space-y-3"><p className="text-xs text-muted-foreground">{text('Lease renewal confirms contact, not work completed. Historical events do not define current failure.', 'تجديد الحجز يثبت الاتصال وليس إنجاز العمل. الأحداث التاريخية لا تحدد الفشل الحالي.')}</p>{data.active_execution?.map(execution => <p key={execution.request_id} className="break-words text-xs">{execution.stage} · {execution.state} · {execution.worker} · {text('Lease expires', 'ينتهي الحجز')}: {stamp(execution.lease_expires_at)}</p>)}<PageEvidence id={data.parent.id} section="events" /></div>}</details>
            </>}
        </>}
    </section>;
}
